server:
  port: 10002
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
minio:
  endpointUrl: http://110.40.190.216:9000
  accessKey: DiscoBroccoli
  secretKey: 1759714344x
  bucketName: gmall
