server:
  port: 10002
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://110.40.190.216:3306/gmall_order?useSSL=false
    username: root
    password: 1759714344x
    driver-class-name: com.mysql.jdbc.Driver
minio:
  endpointUrl: http://110.40.190.216:9000
  accessKey: DiscoBroccoli
  secretKey: 1759714344x
  bucketName: gmall
