server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/*/cart/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
        - id: service-item
          uri: lb://service-item
          predicates:
            - Path=/*/item/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/**/user/**
        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true # Cookie
url:
  pattern:
    direct-pass-url:
      - /css/**
      - /js/**
      - /img/**
      - /fonts/**
    required-auth-url:
      - /**/order/**
    inner-url:
      - /**/inner/**
    login-page: http://passport.gmall.com/login.html
